# Tech/Startup Resume Preset
[theme]
active = "minimal-2"

[style]
primary_font = "Source Sans Pro"
header_font = "Roboto"
font_size = "10pt"
header_font_size = "20pt"
accent_color = "#2563eb"
text_color = "#374151"
link_color = "#2563eb"
header_color = "#1f2937"
paper_size = "us-letter"
margins = "0.5in"
line_spacing = "0.5em"

[formatting]
show_section_lines = true
section_spacing = "0.4em"
entry_spacing = "0.25em"
author_position = "left"
contact_position = "left"
contact_separator = "  |  "

[features]
colored_headers = true
show_footer = false
show_icons = true
profile_picture = false
show_date = true
date_format = "[month repr:long] [day], [year]"

[advanced]
disable_ligatures = true
justify_text = true
hyphenation = false
